In [138]:
import pandas as pd
import tabula
import numpy as np

In [54]:
lista_tabelas = tabula.read_pdf("Reporte_36.pdf", pages="6")
print(len(lista_tabelas))

7

In [57]:
def create_table1():
    df = lista_tabelas[0]
    header = list(df.columns)
    df = df.rename(columns={header[0]: 'Ingenio', 
                   header[1]: 'Superficie industrializada',
                   header[2]: 'Caña molida',
                   header[3]: 'Rendimiento de campo',
                   header[4]: 'Producción de azúcar',
                   header[5]: 'Rendimiento de fábrica',
                   header[6]: 'Rendimiento agroindustrial',
                   header[7]: 'Azúcar refinada',
                   header[8]: 'Azúcar estándar',
                   header[9]: 'Azúcar blanco especial',
                   header[10]: 'Azúcar mascabado',
                       header[11]: 'Azúcar con pol menor a 99.2'})

    df = df.drop([0,1])
    df = df.where(pd.notnull(df), None)
    df = df.replace(' ', '', regex=True)

    df = df.reset_index(drop = True)
    
    return df

create_table1()

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Producción de azúcar,Rendimiento de fábrica,Rendimiento agroindustrial,Azúcar refinada,Azúcar estándar,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2
0,None,ha,t,t/ha,t,%,tazúcar/ha,t,t,t,t,t
1,Nacional,"787,660","51,179,819",64.98,"5,706,216",11.15,7.24,"1,348,267","3,410,438","182,721","35,876","728,914"
2,Centro,"41,160","3,922,898",95.31,"492,700",12.56,11.97,"21,981","470,719",-,-,-
3,Atencingo*,"14,869","1,653,086",111.18,"213,308",12.90,14.35,-,"213,308",-,-,-
4,CentralCasasano*,"6,914","728,274",105.34,"97,126",13.34,14.05,-,"97,126",-,-,-
5,EmilianoZapata*,"10,994","1,030,126",93.70,"139,069",13.50,12.65,-,"139,069",-,-,-
6,Calipam*,"1,530","100,183",65.48,"8,327",8.31,5.44,-,"8,327",-,-,-
7,ElCarmen*,"6,854","411,229",60.00,"34,870",8.48,5.09,"21,981","12,889",-,-,-

In [32]:
def create_table2():
    df = lista_tabelas[1]
    
    

    return df

create_table2()

,Córdoba - Golfo,"1 31,201","7 ,836,096",5 9.73,"8 43,987",Unnamed: 0,1 0.77,6 .43,"2 04,506","3 92,361","1 2,161","35,876","1 99,083"
0,Central San Miguelito *,"6 ,213","4 25,095",6 8.42,"4 2,233",NaN,9 .93,6 .80,-,"2 ,111",-,"10,110","3 0,013"
1,Central Motzorongo *,"1 7,327","1 ,124,627",6 4.91,"119,682",NaN,1 0.64,6 .91,-,"7 5,411",-,-,"4 4,271"
2,San Nicolás *,"1 5,490","9 93,005",6 4.11,"9 8,400",NaN,9.91,6 .35,"8 1,564","5 ,190",-,"2,698","8 ,948"
3,Central El Potrero *,"1 9,784","1 ,261,031",6 3.74,"1 35,103",NaN,1 0.71,6 .83,"122,942",-,"1 2,161",-,-
4,Central La Providencia *,"1 1,177","6 76,050",6 0.48,"7 2,450",NaN,1 0.72,6 .48,-,-,-,"2 3,068","4 9,382"
5,Constancia *,"1 0,886","6 31,296",57.99,"6 3,562",NaN,1 0.07,5 .84,-,"6 3,562",-,-,-
6,El Refugio *,"6 ,554","370,136",5 6.48,"3 9,802",NaN,1 0.75,6 .07,-,"1 4,393",-,-,"2 5,408"
7,La Margarita *,"1 8,826","1 ,002,119",5 3.23,"1 19,152",NaN,1 1.89,6 .33,-,"8 7,193",-,-,"3 1,959"
8,Central Progreso *,"1 2,525","6 43,683",51.39,"79,184",NaN,1 2.30,6 .32,-,"70,083",-,-,"9 ,101"
9,San José de Abajo *,"1 2,419","7 09,054",5 7.09,"7 4,418",NaN,1 0.50,5 .99,-,"7 4,418",-,-,-

In [114]:
def create_table3():
    df = lista_tabelas[2]
    
    
    header = list(df.columns)
    header[:] = [x for x in header if not x.startswith('Unnamed:')]
    print(len(header))
    print(header)
        
    df = df.rename(columns={
                       header[0]: 'Ingenio', 
                       header[1]: 'Superficie industrializada',
                       header[2]: 'Caña molida',
                       header[3]: 'Rendimiento de campo',
                       header[4]: 'Producción de azúcar',
                       header[5]: 'Rendimiento de fábrica',
                       header[6]: 'Rendimiento agroindustrial',
                       header[7]: 'Azúcar refinada',
                       header[8]: 'Azúcar estándar',
                       header[9]: 'Azúcar blanco especial',
                       header[10]: 'Azúcar mascabado',
                       header[11]: 'Azúcar con pol menor a 99.2'})
    
    df = df.drop(columns=["Unnamed: 0", "Unnamed: 1"])
    df = df.append(pd.Series(header, index=df.columns[:len(header)]), ignore_index=True)
    df = df.replace('-.1', '-', regex=True)
    df = df.where(pd.notnull(df), None)
    df = df.replace(' ', '', regex=True)

    df = df.reset_index(drop = True)
   
    
    return df

create_table3()

12
['Noreste', '1 74,243', '9 ,868,764', '56.64', '1 ,156,265', '11.72', '6 .64', '369,830', '7 11,797', '-', '-.1', '7 4,638']

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Producción de azúcar,Rendimiento de fábrica,Rendimiento agroindustrial,Azúcar refinada,Azúcar estándar,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2
0,Pánuco*,"30,968","2,045,977",66.07,"230,175",11.25,7.43,-,"155,537",-,-,"74,638"
1,ElHigo*,"23,649","1,501,174",63.48,"169,259",11.28,7.16,-,"169,259",-,-,-
2,PlandeAyala*,"20,126","1,253,994",62.31,"147,527",11.76,7.33,"147,527",-,-,-,-
3,ElMante*,"17,031","1,007,793",59.17,"113,225",11.23,6.65,-,"113,225",-,-,-
4,PlandeSanLuis*,"21,147","1,167,864",55.22,"142,055",12.16,6.72,"142,055",-,-,-,-
5,AlianzaPopular*,"23,083","1,186,694",51.41,"150,242",12.66,6.51,-,"150,242",-,-,-
6,SanMigueldelNaranjo*,"38,239","1,705,267",44.60,"203,781",11.95,5.33,"80,248","123,533",-,-,-
7,Noreste,"174,243","9,868,764",56.64,"1,156,265",11.72,6.64,"369,830","711,797",-,-,"74,638"

In [141]:
def create_table(index):
    df = lista_tabelas[index]
    
    
    header = list(df.columns)
    header[:] = [x for x in header if not x.startswith('Unnamed:')]
#     print(len(header))
#     print(header)
        
    df = df.rename(columns={
                       header[0]: 'Ingenio', 
                       header[1]: 'Superficie industrializada',
                       header[2]: 'Caña molida',
                       header[3]: 'Rendimiento de campo',
                       header[4]: 'Producción de azúcar',
                       header[5]: 'Rendimiento de fábrica',
                       header[6]: 'Rendimiento agroindustrial',
                       header[7]: 'Azúcar refinada',
                       header[8]: 'Azúcar estándar',
                       header[9]: 'Azúcar blanco especial',
                       header[10]: 'Azúcar mascabado',
                       header[11]: 'Azúcar con pol menor a 99.2'})
    
    
    if index == 2:
        df = df.drop(columns=["Unnamed: 0", "Unnamed: 1"])
        
    df = df.append(pd.Series(header, index=df.columns[:len(header)]), ignore_index=True)
    df = df.replace('-.1', '-', regex=True)
    df = df.where(pd.notnull(df), None)
    df = df.replace(' ', '', regex=True)
    df = df.iloc[np.arange(-1, len(df)-1)]
    df = df.reset_index(drop = True)
    
  
    
    return df

In [144]:
tb2 = create_table(1)
tb2

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Producción de azúcar,Unnamed: 0,Rendimiento de fábrica,Rendimiento agroindustrial,Azúcar refinada,Azúcar estándar,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2
0,Córdoba-Golfo,"131,201","7,836,096",59.73,"843,987",10.77,6.43,"204,506","392,361","12,161","35,876","199,083",None
1,CentralSanMiguelito*,"6,213","425,095",68.42,"42,233",None,9.93,6.80,-,"2,111",-,"10,110","30,013"
2,CentralMotzorongo*,"17,327","1,124,627",64.91,"119,682",None,10.64,6.91,-,"75,411",-,-,"44,271"
3,SanNicolás*,"15,490","993,005",64.11,"98,400",None,9.91,6.35,"81,564","5,190",-,"2,698","8,948"
4,CentralElPotrero*,"19,784","1,261,031",63.74,"135,103",None,10.71,6.83,"122,942",-,"12,161",-,-
5,CentralLaProvidencia*,"11,177","676,050",60.48,"72,450",None,10.72,6.48,-,-,-,"23,068","49,382"
6,Constancia*,"10,886","631,296",57.99,"63,562",None,10.07,5.84,-,"63,562",-,-,-
7,ElRefugio*,"6,554","370,136",56.48,"39,802",None,10.75,6.07,-,"14,393",-,-,"25,408"
8,LaMargarita*,"18,826","1,002,119",53.23,"119,152",None,11.89,6.33,-,"87,193",-,-,"31,959"
9,CentralProgreso*,"12,525","643,683",51.39,"79,184",None,12.30,6.32,-,"70,083",-,-,"9,101"
10,SanJosédeAbajo*,"12,419","709,054",57.09,"74,418",None,10.50,5.99,-,"74,418",-,-,-

In [146]:
tb3 = create_table(2)
tb3

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Producción de azúcar,Rendimiento de fábrica,Rendimiento agroindustrial,Azúcar refinada,Azúcar estándar,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2
0,Noreste,"174,243","9,868,764",56.64,"1,156,265",11.72,6.64,"369,830","711,797",-,-,"74,638"
1,Pánuco*,"30,968","2,045,977",66.07,"230,175",11.25,7.43,-,"155,537",-,-,"74,638"
2,ElHigo*,"23,649","1,501,174",63.48,"169,259",11.28,7.16,-,"169,259",-,-,-
3,PlandeAyala*,"20,126","1,253,994",62.31,"147,527",11.76,7.33,"147,527",-,-,-,-
4,ElMante*,"17,031","1,007,793",59.17,"113,225",11.23,6.65,-,"113,225",-,-,-
5,PlandeSanLuis*,"21,147","1,167,864",55.22,"142,055",12.16,6.72,"142,055",-,-,-,-
6,AlianzaPopular*,"23,083","1,186,694",51.41,"150,242",12.66,6.51,-,"150,242",-,-,-
7,SanMigueldelNaranjo*,"38,239","1,705,267",44.60,"203,781",11.95,5.33,"80,248","123,533",-,-,-

In [147]:
tb4 = create_table(3)
tb4

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Producción de azúcar,Rendimiento de fábrica,Rendimiento agroindustrial,Unnamed: 0,Azúcar refinada,Azúcar estándar,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2
0,Noroeste,"33,621","2,347,316",69.82,"271,916",11.58,8.09,"77,626","124,172","55,702",-,"14,416",None
1,ElMolino*,"11,602","876,377",75.54,"106,548",12.16,9.18,None,-,"106,548",-,-,-
2,Puga*,"17,359","1,167,572",67.26,"136,328",11.68,7.85,None,"77,626","3,000","55,702",-,-
3,Eldorado*,"4,659","303,367",65.11,"29,040",9.57,6.23,None,-,"14,624",-,-,"14,416"

In [148]:
tb5 = create_table(4)
tb5

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Unnamed: 0,Producción de azúcar,Unnamed: 1,Rendimiento de fábrica,Rendimiento agroindustrial,Azúcar refinada,Azúcar estándar,Unnamed: 2,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2
0,Pacífico,"105,433","8,520,659",80.82,"969,542",11.38,9.20,"224,408","662,687","82,448",-,-,None,None,None
1,MelchorOcampo*,"11,518","1,163,278",101.0,None,"140,352",None,12.07,12.19,-,"140,352",None,-,-,-
2,Tamazula*,"14,130","1,291,736",91.42,None,"154,119",None,11.93,10.91,"117,299","36,820",None,-,-,-
3,Tala*,"20,633","1,719,067",83.32,None,"184,851",None,10.75,8.96,"86,057","95,096",None,"3,698",-,-
4,SanFranciscoAmeca*,"12,518","1,032,386",82.47,None,"117,080",None,11.34,9.35,-,"38,394",None,"78,686",-,-
5,SantaClara*,"6,022","480,798",79.84,None,"50,832",None,10.57,8.44,-,"50,832",None,-,-,-
6,Bellavista*,"8,259","644,660",78.05,None,"70,198",None,10.89,8.50,-,"70,198",None,-,-,-
7,Pedernales*,"3,564","278,104",78.02,None,"31,769",None,11.42,8.91,-,"31,769",None,-,-,-
8,LázaroCárdenas*,"3,339","248,740",74.5,None,"28,708",None,11.54,8.60,"21,052","7,656",None,-,-,-
9,Quesería*,"15,794","1,036,520",65.63,None,"125,058",None,12.07,7.92,-,"124,993",None,65,-,-
10,JoséMaríaMorelos*,"9,657","625,372",64.76,None,"66,577",None,10.65,6.89,-,"66,577",None,-,-,-

In [149]:
tb6 = create_table(5)
tb6

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Producción de azúcar,Rendimiento de fábrica,Rendimiento agroindustrial,Azúcar refinada,Azúcar estándar,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2
0,Papaloapan-Golfo,"182,663","10,996,012",60.20,"1,150,210",10.46,6.30,"374,256","582,605",-,-,"193,349"
1,ElModelo*,"11,403","1,052,464",92.30,"108,816",10.34,9.54,-,"104,298",-,-,"4,518"
2,LaGloria*,"19,926","1,655,626",83.09,"184,201",11.13,9.24,-,"184,201",-,-,-
3,Mahuixtlán*,"6,224","432,701",69.52,"45,639",10.55,7.33,-,"45,639",-,-,-
4,AdolfoLópezMateos*,"23,250","1,446,821",62.23,"139,018",9.61,5.98,"139,018",-,-,-,-
5,SanPedro*,"18,130","1,110,383",61.25,"104,372",9.40,5.76,-,"104,372",-,-,-
6,TresValles*,"41,495","2,135,791",51.47,"235,238",11.01,5.67,"235,238",-,-,-,-
7,CIASA(Cuatotolapam)*,"16,274","836,555",51.41,"94,003",11.24,5.78,-,"36,959",-,-,"57,044"
8,SanCristóbal*,"45,962","2,325,671",50.60,"238,922",10.27,5.2,-,"107,135",-,-,"131,787"

In [150]:
tb7 = create_table(6)
tb7

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Producción de azúcar,Unnamed: 0,Rendimiento de fábrica,Rendimiento agroindustrial,Azúcar refinada,Azúcar estándar,Unnamed: 1,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2
0,Sureste,"119,338","7,688,072",64.42,"821,596",10.69,6.88,"75,660","466,098","32,410",-,"247,428",None,None
1,Cía.LaFe(Pujiltic)*,"17,209","1,696,248",98.57,"215,335",None,12.69,12.51,-,"215,335",None,-,-,-
2,Huixtla*,"14,507","1,258,582",86.76,"123,145",None,9.78,8.49,-,"57,149",None,-,-,"65,996"
3,SantaRosalía*,"12,113","685,066",56.56,"71,980",None,10.51,5.94,-,-,None,-,-,"71,980"
4,SanRafaeldePucté,"30,778","1,681,877",54.65,"164,329",None,9.77,5.34,-,"84,441",None,-,-,"79,888"
5,LaJoya*,"18,520","993,914",53.67,"104,527",None,10.52,5.64,-,"74,963",None,-,-,"29,564"
6,PresidenteBenitoJuárez*,"26,212","1,372,384",52.36,"142,280",None,10.37,5.43,"75,660","34,210",None,"32,410",-,-

In [153]:
tb1 = create_table1()
tb1

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Producción de azúcar,Rendimiento de fábrica,Rendimiento agroindustrial,Azúcar refinada,Azúcar estándar,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2
0,None,ha,t,t/ha,t,%,tazúcar/ha,t,t,t,t,t
1,Nacional,"787,660","51,179,819",64.98,"5,706,216",11.15,7.24,"1,348,267","3,410,438","182,721","35,876","728,914"
2,Centro,"41,160","3,922,898",95.31,"492,700",12.56,11.97,"21,981","470,719",-,-,-
3,Atencingo*,"14,869","1,653,086",111.18,"213,308",12.90,14.35,-,"213,308",-,-,-
4,CentralCasasano*,"6,914","728,274",105.34,"97,126",13.34,14.05,-,"97,126",-,-,-
5,EmilianoZapata*,"10,994","1,030,126",93.70,"139,069",13.50,12.65,-,"139,069",-,-,-
6,Calipam*,"1,530","100,183",65.48,"8,327",8.31,5.44,-,"8,327",-,-,-
7,ElCarmen*,"6,854","411,229",60.00,"34,870",8.48,5.09,"21,981","12,889",-,-,-

In [154]:
display(pd.concat([tb1, tb2, tb3, tb4, tb5, tb6, tb7], ignore_index=True))

,Ingenio,Superficie industrializada,Caña molida,Rendimiento de campo,Producción de azúcar,Rendimiento de fábrica,Rendimiento agroindustrial,Azúcar refinada,Azúcar estándar,Azúcar blanco especial,Azúcar mascabado,Azúcar con pol menor a 99.2,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,None,ha,t,t/ha,t,%,tazúcar/ha,t,t,t,t,t,NaN,NaN,NaN
1,Nacional,"787,660","51,179,819",64.98,"5,706,216",11.15,7.24,"1,348,267","3,410,438","182,721","35,876","728,914",NaN,NaN,NaN
2,Centro,"41,160","3,922,898",95.31,"492,700",12.56,11.97,"21,981","470,719",-,-,-,NaN,NaN,NaN
3,Atencingo*,"14,869","1,653,086",111.18,"213,308",12.90,14.35,-,"213,308",-,-,-,NaN,NaN,NaN
4,CentralCasasano*,"6,914","728,274",105.34,"97,126",13.34,14.05,-,"97,126",-,-,-,NaN,NaN,NaN
5,EmilianoZapata*,"10,994","1,030,126",93.70,"139,069",13.50,12.65,-,"139,069",-,-,-,NaN,NaN,NaN
6,Calipam*,"1,530","100,183",65.48,"8,327",8.31,5.44,-,"8,327",-,-,-,NaN,NaN,NaN
7,ElCarmen*,"6,854","411,229",60.00,"34,870",8.48,5.09,"21,981","12,889",-,-,-,NaN,NaN,NaN
8,Córdoba-Golfo,"131,201","7,836,096",59.73,"843,987",6.43,"204,506","392,361","12,161","35,876","199,083",None,10.77,NaN,NaN
9,CentralSanMiguelito*,"6,213","425,095",68.42,"42,233",9.93,6.80,-,"2,111",-,"10,110","30,013",None,NaN,NaN
10,CentralMotzorongo*,"17,327","1,124,627",64.91,"119,682",10.64,6.91,-,"75,411",-,-,"44,271",None,NaN,NaN
11,SanNicolás*,"15,490","993,005",64.11,"98,400",9.91,6.35,"81,564","5,190",-,"2,698","8,948",None,NaN,NaN
12,CentralElPotrero*,"19,784","1,261,031",63.74,"135,103",10.71,6.83,"122,942",-,"12,161",-,-,None,NaN,NaN
13,CentralLaProvidencia*,"11,177","676,050",60.48,"72,450",10.72,6.48,-,-,-,"23,068","49,382",None,NaN,NaN
14,Constancia*,"10,886","631,296",57.99,"63,562",10.07,5.84,-,"63,562",-,-,-,None,NaN,NaN
15,ElRefugio*,"6,554","370,136",56.48,"39,802",10.75,6.07,-,"14,393",-,-,"25,408",None,NaN,NaN
16,LaMargarita*,"18,826","1,002,119",53.23,"119,152",11.89,6.33,-,"87,193",-,-,"31,959",None,NaN,NaN
17,CentralProgreso*,"12,525","643,683",51.39,"79,184",12.30,6.32,-,"70,083",-,-,"9,101",None,NaN,NaN
18,SanJosédeAbajo*,"12,419","709,054",57.09,"74,418",10.50,5.99,-,"74,418",-,-,-,None,NaN,NaN
19,Noreste,"174,243","9,868,764",56.64,"1,156,265",11.72,6.64,"369,830","711,797",-,-,"74,638",NaN,NaN,NaN
20,Pánuco*,"30,968","2,045,977",66.07,"230,175",11.25,7.43,-,"155,537",-,-,"74,638",NaN,NaN,NaN
21,ElHigo*,"23,649","1,501,174",63.48,"169,259",11.28,7.16,-,"169,259",-,-,-,NaN,NaN,NaN
22,PlandeAyala*,"20,126","1,253,994",62.31,"147,527",11.76,7.33,"147,527",-,-,-,-,NaN,NaN,NaN
23,ElMante*,"17,031","1,007,793",59.17,"113,225",11.23,6.65,-,"113,225",-,-,-,NaN,NaN,NaN
24,PlandeSanLuis*,"21,147","1,167,864",55.22,"142,055",12.16,6.72,"142,055",-,-,-,-,NaN,NaN,NaN
25,AlianzaPopular*,"23,083","1,186,694",51.41,"150,242",12.66,6.51,-,"150,242",-,-,-,NaN,NaN,NaN
26,SanMigueldelNaranjo*,"38,239","1,705,267",44.60,"203,781",11.95,5.33,"80,248","123,533",-,-,-,NaN,NaN,NaN
27,Noroeste,"33,621","2,347,316",69.82,"271,916",11.58,8.09,"124,172","55,702",-,"14,416",None,"77,626",NaN,NaN
28,ElMolino*,"11,602","876,377",75.54,"106,548",12.16,9.18,-,"106,548",-,-,-,None,NaN,NaN
29,Puga*,"17,359","1,167,572",67.26,"136,328",11.68,7.85,"77,626","3,000","55,702",-,-,None,NaN,NaN
30,Eldorado*,"4,659","303,367",65.11,"29,040",9.57,6.23,-,"14,624",-,-,"14,416",None,NaN,NaN
31,Pacífico,"105,433","8,520,659",80.82,11.38,"224,408","662,687","82,448",-,None,None,None,"969,542",9.20,-
32,MelchorOcampo*,"11,518","1,163,278",101.0,"140,352",12.07,12.19,-,"140,352",-,-,-,None,None,None
33,Tamazula*,"14,130","1,291,736",91.42,"154,119",11.93,10.91,"117,299","36,820",-,-,-,None,None,None
34,Tala*,"20,633","1,719,067",83.32,"184,851",10.75,8.96,"86,057","95,096","3,698",-,-,None,None,None
35,SanFranciscoAmeca*,"12,518","1,032,386",82.47,"117,080",11.34,9.35,-,"38,394","78,686",-,-,None,None,None
36,SantaClara*,"6,022","480,798",79.84,"50,832",10.57,8.44,-,"50,832",-,-,-,None,None,None
37,Bellavista*,"8,259","644,660",78.05,"70,198",10.89,8.50,-,"70,198",-,-,-,None,None,None
38,Pedernales*,"3,564","278,104",78.02,"31,769",11.42,8.91,-,"31,769",-,-,-,None,None,None
39,LázaroCárdenas*,"3,339","248,740",74.5,"28,708",11.54,8.60,"21,052","7,656",-,-,-,None,None,None
40,Quesería*,"15,794","1,036,520",65.63,"125,058",12.07,7.92,-,"124,993",65,-,-,None,None,None
41,JoséMaríaMorelos*,"9,657","625,372",64.76,"66,577",10.65,6.89,-,"66,577",-,-,-,None,None,None
42,Papaloapan-Golfo,"182,663","10,996,012",60.20,"1,150,210",10.46,6.30,"374,256","582,605",-,-,"193,349",NaN,NaN,NaN
43,ElModelo*,"11,403","1,052,464",92.30,"108,816",10.34,9.54,-,"104,298",-,-,"4,518",NaN,NaN,NaN
44,LaGloria*,"19,926","1,655,626",83.09,"184,201",11.13,9.24,-,"184,201",-,-,-,NaN,NaN,NaN
45,Mahuixtlán*,"6,224","432,701",69.52,"45,639",10.55,7.33,-,"45,639",-,-,-,NaN,NaN,NaN
46,AdolfoLópezMateos*,"23,250","1,446,821",62.23,"139,018",9.61,5.98,"139,018",-,-,-,-,NaN,NaN,NaN
47,SanPedro*,"18,130","1,110,383",61.25,"104,372",9.40,5.76,-,"104,372",-,-,-,NaN,NaN,NaN
48,TresValles*,"41,495","2,135,791",51.47,"235,238",11.01,5.67,"235,238",-,-,-,-,NaN,NaN,NaN
49,CIASA(Cuatotolapam)*,"16,274","836,555",51.41,"94,003",11.24,5.78,-,"36,959",-,-,"57,044",NaN,NaN,NaN
50,SanCristóbal*,"45,962","2,325,671",50.60,"238,922",10.27,5.2,-,"107,135",-,-,"131,787",NaN,NaN,NaN
51,Sureste,"119,338","7,688,072",64.42,"821,596",6.88,"75,660","466,098","32,410","247,428",None,None,10.69,-,NaN
52,Cía.LaFe(Pujiltic)*,"17,209","1,696,248",98.57,"215,335",12.69,12.51,-,"215,335",-,-,-,None,None,NaN
53,Huixtla*,"14,507","1,258,582",86.76,"123,145",9.78,8.49,-,"57,149",-,-,"65,996",None,None,NaN
54,SantaRosalía*,"12,113","685,066",56.56,"71,980",10.51,5.94,-,-,-,-,"71,980",None,None,NaN
55,SanRafaeldePucté,"30,778","1,681,877",54.65,"164,329",9.77,5.34,-,"84,441",-,-,"79,888",None,None,NaN
56,LaJoya*,"18,520","993,914",53.67,"104,527",10.52,5.64,-,"74,963",-,-,"29,564",None,None,NaN
57,PresidenteBenitoJuárez*,"26,212","1,372,384",52.36,"142,280",10.37,5.43,"75,660","34,210","32,410",-,-,None,None,NaN